title: "Milind Patil"
name: "Milind Patil"
description: "Researcher in AI/ML for Wireless Communications, CSI Sensing, mmWave/6G Systems â€” Seeking Research Opportunities"

email: "milind1995@gmail.com"
url: "https://milindap.github.io"
baseurl: ""

theme: minima

minima:
  skin: light
  social_links:
    - platform: github
      user_url: "https://github.com/milindap"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/milind-patil-97b676122/"
    - platform: rss
    - platform: researchgate
      user_url: "https://www.researchgate.net/profile/Milind-Patil-30"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  teaching:
    output: true
    permalink: /teaching/:path/

header_pages:
  - index.md
  - about.md
  - research.md
  - publications.html
  - projects.md
  - teaching.html
  - cv.html
  - contact.md
